import React from "react";
import { StyleSheet, StatusBar, Dimensions, Platform} from "react-native";

//TODO: Add icon set here
export const react_colors = {
  primaryblue: "#0066cc",
  primarygreen: "#00cc99",
  primaryyellow: "#ffcc66",
  complementaryblue: "#003366",
  complementarynavy: "#00cccc",
  complementarygray: "#96939B",
  shadowblue: "#0066cc21",
  aliceblue: "#f0f8ff",
  antiflashwhite: "#ebf5f3",
  antiquewhite: "#faebd7",
  aqua: "#00ffff",
  aquamarine: "#7fffd4",
  azure: "#f0ffff",
  beige: "#f5f5dc",
  bisque: "#ffe4c4",
  black: "#000000",
  blanchedalmond: "#ffebcd",
  blue: "#0000ff",
  blueviolet: "#8a2be2",
  brown: "#a52a2a",
  burlywood: "#deb887",
  cadetblue: "#5f9ea0",
  chartreuse: "#7fff00",
  chocolate: "#d2691e",
  coral: "#ff7f50",
  cornflowerblue: "#6495ed",
  cornsilk: "#fff8dc",
  crimson: "#dc143c",
  cyan: "#00ffff",
  darkblue: "#00008b",
  darkcyan: "#008b8b",
  darkgoldenrod: "#b8860b",
  darkgray: "#a9a9a9",
  darkgreen: "#006400",
  darkgrey: "#a9a9a9",
  darkkhaki: "#bdb76b",
  darkmagenta: "#8b008b",
  darkolivegreen: "#556b2f",
  darkorange: "#ff8c00",
  darkorchid: "#9932cc",
  darkred: "#8b0000",
  darksalmon: "#e9967a",
  darkseagreen: "#8fbc8f",
  darkslateblue: "#483d8b",
  darkslategrey: "#2f4f4f",
  darkturquoise: "#00ced1",
  darkviolet: "#9400d3",
  deeppink: "#ff1493",
  deepskyblue: "#00bfff",
  dimgray: "#696969",
  dimgrey: "#696969",
  dodgerblue: "#1e90ff",
  firebrick: "#b22222",
  floralwhite: "#fffaf0",
  forestgreen: "#228b22",
  fuchsia: "#ff00ff",
  gainsboro: "#dcdcdc",
  ghostwhite: "#f8f8ff",
  gold: "#ffd700",
  goldenrod: "#daa520",
  gray: "#808080",
  green: "#008000",
  greenyellow: "#adff2f",
  grey: "#808080",
  honeydew: "#f0fff0",
  hotpink: "#ff69b4",
  interconnect: "#fdcb46",
  indianred: "#cd5c5c",
  indigo: "#4b0082",
  ivory: "#fffff0",
  khaki: "#f0e68c",
  lavender: "#e6e6fa",
  lavenderblush: "#fff0f5",
  lawngreen: "#7cfc00",
  lemonchiffon: "#fffacd",
  lightblue: "#add8e6",
  lightcoral: "#f08080",
  lightcyan: "#e0ffff",
  lightgoldenrodyellow: "#fafad2",
  lightgray: "#d3d3d3",
  lightgreen: "#90ee90",
  lightgrey: "#d3d3d3",
  lightpink: "#ffb6c1",
  lightsalmon: "#ffa07a",
  lightseagreen: "#20b2aa",
  lightskyblue: "#87cefa",
  lightslategrey: "#778899",
  lightsteelblue: "#b0c4de",
  lightyellow: "#ffffe0",
  lime: "#00ff00",
  limegreen: "#32cd32",
  linen: "#faf0e6",
  magenta: "#ff00ff",
  maroon: "#800000",
  mediumaquamarine: "#66cdaa",
  mediumblue: "#0000cd",
  mediumorchid: "#ba55d3",
  mediumpurple: "#9370db",
  mediumseagreen: "#3cb371",
  mediumslateblue: "#7b68ee",
  mediumspringgreen: "#00fa9a",
  mediumturquoise: "#48d1cc",
  mediumvioletred: "#c71585",
  midnightblue: "#191970",
  mintcream: "#f5fffa",
  mistyrose: "#ffe4e1",
  moccasin: "#ffe4b5",
  navajowhite: "#ffdead",
  navy: "#000080",
  oldlace: "#fdf5e6",
  olive: "#808000",
  olivedrab: "#6b8e23",
  orange: "#ffa500",
  orangered: "#ff4500",
  orchid: "#da70d6",
  palegoldenrod: "#eee8aa",
  palegreen: "#98fb98",
  paleturquoise: "#afeeee",
  palevioletred: "#db7093",
  papayawhip: "#ffefd5",
  peachpuff: "#ffdab9",
  peru: "#cd853f",
  pink: "#ffc0cb",
  plum: "#dda0dd",
  powderblue: "#b0e0e6",
  purple: "#800080",
  rebeccapurple: "#663399",
  red: "#ff0000",
  rosybrown: "#bc8f8f",
  royalblue: "#4169e1",
  saddlebrown: "#8b4513",
  salmon: "#fa8072",
  sandybrown: "#f4a460",
  seagreen: "#2e8b57",
  seashell: "#fff5ee",
  sienna: "#a0522d",
  silver: "#c0c0c0",
  skyblue: "#87ceeb",
  slateblue: "#6a5acd",
  slategray: "#708090",
  snow: "#fffafa",
  springgreen: "#00ff7f",
  steelblue: "#4682b4",
  tan: "#d2b48c",
  teal: "#008080",
  thistle: "#d8bfd8",
  tiffanyblue: "#9ACFC1",
  tomato: "#ff6347",
  turquoise: "#40e0d0",
  violet: "#ee82ee",
  wheat: "#f5deb3",
  white: "#ffffff",
  whitesmoke: "#f5f5f5",
  yellow: "#ffff00",
  yellowgreen: "#9acd32",
};

export const color_status = {
  on: react_colors.mediumseagreen,
  off: react_colors.black,
  other: react_colors.coral,
};

export const styles = StyleSheet.create({
  container: {
    // paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    flex: 1,
    // height: "100%",
    // alignItems: "center",
    // justifyContent: "center",
    // backgroundColor: "#ccc",
  },
  row_container: {
    // backgroundColor: "#ddd",
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-evenly",
    // alignItems: "flex-start", //cross axis
    // alignContent: "stretch", //cross axis
  },
  view_container: {
    // backgroundColor: "#ddd",
    // flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    // alignContent: "center",
  },
  view_item: {
    // backgroundColor: "#ccc",
    width: "90%",
    alignSelf: "center",
    // justifyContent: "space-evenly",
  },
  view_item_left: {
    width: "7%",
    // justifyContent: "center",
  },
  card:
    Platform.OS === "android"
      ? {
          top: 0,
          elevation: 10,
        }
      : { top: 0, zIndex: 10 },
  card_img: {
    // width: "80%",
    height: 120,
    // backgroundColor: react_colors.complementaryblue,
    // flex: 1,
    // justifyContent: "center",
    // alignItems: "baseline",
    // flexWrap: "nowrap",
  },
  divider: { height: 20 },
  graph_view: {
    width: 300,
    height: 280,
  },
  prefs_btn: {
    width: "80%",
    alignSelf: "center",
  },
  listNode: {
    borderColor: react_colors.complementarygray,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: react_colors.antiflashwhite,
  },
  input: {
    height: 42,
    borderColor: "transparent",
    borderWidth: 1,
    borderRadius: 5,
    // paddingHorizontal: 5,
    // flexDirection: "row",
    // alignItems: "center",
    // backgroundColor: react_colors.whitesmoke,
    backgroundColor: "transparent",
    marginBottom: 20,
  },
  list_item: {
    borderWidth: 1,
    borderRadius: 5,
    borderColor: react_colors.mediumslateblue,
  },
  erro: {
    borderWidth: 1,
    borderRadius: 5,
    borderColor: "#ff0000",
  },

  global_color: { backgroundColor: react_colors.antiflashwhite },

  input_transp: {
    borderBottomColor: react_colors.white,
    borderColor: "transparent",
    borderWidth: StyleSheet.hairlineWidth,
    color: react_colors.black,
    fontSize: 16,
    paddingVertical: 12 * 0.5,
  },
  inputContainer: {
    marginBottom: 8 * 2,
    width: "90%",
    // backgroundColor: react_colors.ivory,
  },
  checkbox: Platform.OS !== "android" && {
    width: 30,
    height: 30,
    borderWidth: 0.4,
    alignItems: "center",
    borderRadius: 10,
  },
  calItem: {
    padding: 20,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "lightgrey",
    flexDirection: "row",
  },
  calItemHourText: {
    color: "black",
  },
  calItemDurationText: {
    color: "grey",
    fontSize: 12,
    marginTop: 4,
    // marginLeft: 16,
  },
  calItemTitleText: {
    color: "black",
    marginLeft: 16,
    fontWeight: "bold",
    fontSize: 14,
  },
  calItemButtonContainer: {
    width: "18%",
    // flex: 1,
    alignItems: "flex-end",
  },
  calItemButtonContainer2: {
    width: "82%",
    marginRight: 6,
    // flex: 1,
    alignItems: "flex-start",
  },
  calEmptyItem: {
    paddingLeft: 20,
    height: 52,
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: "lightgrey",
  },
  calEmptyItemText: {
    color: "lightgrey",
    fontSize: 14,
  },
  dataTableCell: {
    marginHorizontal: 3,
    width: "33%",
  },
  dataTableAColumn: {
    width: "33%",
  },
  dataTableHighRow: {
    height: 70,
  },
  dataTable: {
    width: "90%",
    alignSelf: "center",
  },
  dataTableMultilineCell: {
    marginHorizontal: 3,
    width: "33%",
    height: 70,
  },
  wtdview: {
    alignSelf: "center",
    alignContent: "center",
    width: "90%",
    backgroundColor: react_colors.lightgray,
    paddingVertical: 3,
    paddingHorizontal: 5,
  },

  //para sair
  contentShadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3.84,
    elevation: 3,
  },
  row: {
    padding: 16,
    paddingLeft: 16,
    paddingRight: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  user: {
    width: Dimensions.get("screen").width - 32,
    alignSelf: "center",
    marginVertical: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  info: {
    marginLeft: 10,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 100,
  },
  name: {
    color: "#424242",
    fontSize: 16,
    fontWeight: "600",
  },
  email: {
    marginTop: 6,
    color: "#888",
  },
});
